  name: Java CI 01 for compile sources
  run-name: ${{ github.actor }} runs compile sources 🚀
  on: [push]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Set up JDK 19
          uses: actions/setup-java@v3
          with:
            java-version: '19'
            distribution: 'adopt'
        - name: Build with Maven
          run: mvn --batch-mode --update-snapshots package
          
          # Docker Run: docker login -u mpoettler
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.mpoettler }}
            password: ${{ secrets.dckr_pat_WdLzNaX0HdafbQ0JjKfSgDtZER4 }}
            
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          
        - name: Build and push to public repository
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.mpoettler }}/democalc_public:latest
          
          
