name: Java CI 04 with Checkstyle
run-name: ${{ github.actor }} checks Java Style
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@0.6.0
