name: Java CI 04 with Checkstyle
run-name: ${{ github.actor }} checks Java Style
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-check'
          tool_name: 'testtool'
          level: 'error'
          fail_on_error: true
